set_attribute -type boolean [get_pins sda_pad/PAD] is_pad true
set_attribute -type boolean [get_pins scl_pad/PAD] is_pad true
set_attribute -type boolean [get_pins ackflag_pad_2/PAD] is_pad true
set_attribute -type boolean [get_pins ackflag_pad_1/PAD] is_pad true
set_attribute -type boolean [get_pins ackflag_pad_0/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_7/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_6/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_5/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_4/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_3/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_2/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_1/PAD] is_pad true
set_attribute -type boolean [get_pins outdata_pad_0/PAD] is_pad true
set_attribute -type boolean [get_pins sw4_pad/PAD] is_pad true
set_attribute -type boolean [get_pins sw3_pad/PAD] is_pad true
set_attribute -type boolean [get_pins sw2_pad/PAD] is_pad true
set_attribute -type boolean [get_pins sw1_pad/PAD] is_pad true
set_attribute -type boolean [get_pins addr_pad_2/PAD] is_pad true
set_attribute -type boolean [get_pins addr_pad_1/PAD] is_pad true
set_attribute -type boolean [get_pins addr_pad_0/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_7/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_6/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_5/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_4/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_3/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_2/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_1/PAD] is_pad true
set_attribute -type boolean [get_pins IDAT_pad_0/PAD] is_pad true
set_attribute -type boolean [get_pins REG_WR_pad/PAD] is_pad true
set_attribute -type boolean [get_pins rst_n_pad/PAD] is_pad true
set_attribute -type boolean [get_pins clk_pad/PAD] is_pad true
