set_pns_commit_mode true
# Starting to commit core rings
create_power_straps  -direction vertical  -start_at 1119.920 -nets VDD -layer 18 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 351.250 -nets VDD -layer 18 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 351.250 -nets VDD -layer 22 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1119.870 -nets VDD -layer 22 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 1109.270 -nets VSS -layer 18 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction vertical  -start_at 361.900 -nets VSS -layer 18 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 361.910 -nets VSS -layer 22 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
create_power_straps  -direction horizontal  -start_at 1109.210 -nets VSS -layer 22 -width 10.000 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -keep_floating_wire_pieces -ignore_parallel_targets -define_parallel_targets_by_wire_directions -mark_as_ring
# Starting to commit block rings
# Starting to commit metal4 straps for net VDD
create_power_straps  -direction vertical  -start_at 460.415 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 551.575 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 642.725 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 733.885 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 825.035 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 916.195 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1007.345 -nets VDD  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.870 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal4 straps for net VSS
create_power_straps  -direction vertical  -start_at 463.735 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 554.885 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 646.045 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 737.195 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 828.355 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 919.505 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction vertical  -start_at 1010.665 -nets VSS  -layer 26 -width 2.710 -pitch_within_group 91.080 -start_low_ends coordinate  -start_low_ends_coordinate 356.910 -start_high_ends coordinate  -start_high_ends_coordinate 1114.210 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VDD
create_power_straps  -direction horizontal  -start_at 460.505 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 552.035 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 642.755 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 733.475 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 825.005 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 915.725 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1007.255 -nets VDD  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 346.250 -start_high_ends coordinate  -start_high_ends_coordinate 1124.920 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
# Starting to commit metal5 straps for net VSS
create_power_straps  -direction horizontal  -start_at 463.815 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 555.345 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 646.065 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 736.785 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 828.315 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 919.035 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
create_power_straps  -direction horizontal  -start_at 1010.565 -nets VSS  -layer 30 -width 2.710 -pitch_within_group 91.070 -start_low_ends coordinate  -start_low_ends_coordinate 356.900 -start_high_ends coordinate  -start_high_ends_coordinate 1114.270 -extend_low_ends off -extend_high_ends off -num_placement_strap 1 -keep_floating_wire_pieces  -ignore_parallel_targets -define_parallel_targets_by_wire_directions 
set_pns_commit_mode false
